//
//  NotificationConstants.h
//  Emotish
//
//  Created by Dan Bretl on 3/2/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#ifndef Emotish_NotificationConstants_h
#define Emotish_NotificationConstants_h

#define NOTIFICATION_APPLICATION_DID_BECOME_ACTIVE @"NOTIFICATION_APPLICATION_DID_BECOME_ACTIVE"
#define NOTIFICATION_USER_INFO_KEY_APPLICATION_OPENED_URL @"NOTIFICATION_USER_INFO_KEY_APPLICATION_OPENED_URL"

#define NOTIFICATION_NAVIGATE_TO_USER_PHOTO @"NOTIFICATION_NAVIGATE_TO_USER_PHOTO"
#define NOTIFICATION_NAVIGATE_TO_USER_PHOTO_KEY_USER_SERVER_ID @"NOTIFICATION_NAVIGATE_TO_USER_PHOTO_KEY_USER_SERVER_ID"
#define NOTIFICATION_NAVIGATE_TO_USER_PHOTO_KEY_PHOTO_SERVER_ID @"NOTIFICATION_NAVIGATE_TO_USER_PHOTO_KEY_PHOTO_SERVER_ID"

#endif